// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI operations (migrate, introspect, generate) need a direct connection —
  // the pooled DATABASE_URL (pgbouncer, port 6543) hangs on these commands.
  // The app's own pg Pool and any future PrismaClient driver adapter keep using
  // DATABASE_URL directly, independent of this config.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
